using System;
using System.Collections.Generic;
using InmobiliariasHomeCo.Entities.Currencies;
using InmobiliariasHomeCo.Entities.Properties;
using InmobiliariasHomeCo.Entities.Persons.Owners;
using InmobiliariasHomeCo.Entities.Security;

namespace InmobiliariasHomeCo.Entities.Pojos.Properties
{
    public class PropertyMessage: DatesSecurity
    {
        
        public string               SearchProperty { get; set; }
        public int                     IdProperty               { get; set; }
        public int                      IdPropertyType            { get; set; }
        public int                      IdCountry               { get; set; }
        public int                      IdState                 { get; set; }
        public int                      IdZone                  { get; set; }
        public string                  PropertyKey           { get; set; }
        public string                  CaptureDate           { get; set; }
        public string                  StateKey              { get; set; }
        public string                  State                 { get; set; }
        public string                  Key                   { get; set; }
        public string                  PropertyType          { get; set; }
        public string                  PropertyTypeKey       { get; set; }
        public string                  PropertySubType       { get; set; }
        public string                  PropertySubTypeKey    { get; set; }
        public string                  Descripcion           { get; set; }        
        public string                  CountryKey            { get; set; }
        public string                  ColonyKey             { get; set; }
        public string                  Colony                { get; set; }
        public string                  PostCode              { get; set; }
        public string                  CityKey               { get; set; }
        public string                  City                  { get; set; }
        public string                  PriceMax              { get; set; }
        public string                  PriceMin              { get; set; }
        public string                  NumRooms              { get; set; }
        public string                  NumBath               { get; set; }
        public string                  UserName              { get; set; }
        public string                  Id_Rol                { get; set; }
        public string                  FullName              { get; set; }
        public string                  CreateDate            { get; set; }
        public string                  IsEnabled             { get; set; }
        public string                  IsAdminBms            { get; set; }
        public string                  Email                 { get; set; }
        public string                  Nombre                { get; set; }
        public string                  Asunto                { get; set; }
        public string                  Mensaje               { get; set; }
        public string                  Operation             { get; set; }
        public string                  GroudType             { get; set; }
        public string                  Sector                { get; set; }
        public string                  TypeOperationKey      { get; set; }
        public string                  GroundKey             { get; set; }
        public string                  SectorKey             { get; set; }
        public string                  ZoneKey               { get; set; }
        public string                  Zone                  { get; set; }
        public string                  SourceKey             { get; set; }
        public string                  Source                { get; set; }
        public string                  RegDate               { get; set; }
        public string                  Name                  { get; set; }
        public string                  PhoneNumber           { get; set; }
        public string                  MobilNumber           { get; set; }
        public string                  BirthDate             { get; set; }
        public string                  MaritalStatus         { get; set; }
        public string                  Id_Gender             { get; set; }
        public string                  ChildrenNUmber        { get; set; }
        public string                  InitialDate           { get; set; }
        public string                  Title                 { get; set; }
        public string                  URLPhoto              { get; set; }
        public string                  TaxRef                { get; set; }
        public string                  Id_Bank               { get; set; }
        public string                  BankReference         { get; set; }
        public string                  Id_SalesRep           { get; set; }
        public string                  Id_Person             { get; set; }
        public string                  Id_Owner              { get; set; }
        public string                  Id_Property           { get; set; }
        public string                  Street                { get; set; }
        public string                  Id_Colony             { get; set; }
        public string                  OutdoorNumber         { get; set; }
        public string                  InteriorNumber        { get; set; }
        public string                  Id_Address            { get; set; }
        public string                  Id_Ground             { get; set; }
        public string                  Area                  { get; set; }
        public string                  GardenArea            { get; set; }
        public string                  Construction          { get; set; }
        public string                  Levels                { get; set; }
        public string                  Front                 { get; set; }
        public string                  BackGround            { get; set; }
        public string                  Description           { get; set; }
        public string                  AntiguatyYears        { get; set; }
        public string                  Tank                  { get; set; }
        public string                  CapacityTank          { get; set; }
        public string                  CurrentPredial        { get; set; }
        public string                  CurrentMaintenance    { get; set; }
        public string                  ServicesPayed         { get; set; }
        public string                  Id_Currency           { get; set; }
        public string                  FiscalReceipt         { get; set; }
        public string                  Id_PropertyType       { get; set; }
        public string                  Id_PropertySubType    { get; set; }
        public string                  Others                { get; set; }
        public string                  TypeOperation         { get; set; }
        public string                  SportFields           { get; set; }
        public string                  Spit                  { get; set; }
        public string                  Rooms                 { get; set; }
        public string                  Closet                { get; set; }
        public string                  DressingRoom          { get; set; }
        public string                  Bath                  { get; set; }
        public string                  MiddleBath            { get; set; }
        public string                  ServiceCorridor       { get; set; }
        public string                  ServiceRoom           { get; set; }
        public string                  Parking               { get; set; }
        public string                  ParkingVisit          { get; set; }
        public string                  Cellar                { get; set; }
        public string                  Kitchen               { get; set; }
        public string                  FretsSoap             { get; set; }
        public string                  TvRoom                { get; set; }
        public string                  StudyRoom             { get; set; }
        public string                  Bar                   { get; set; }
        public string                  ServiceYard           { get; set; }
        public string                  MultipleSalon         { get; set; }
        public string                  Smokestack            { get; set; }
        public string                  Jacuzzi               { get; set; }
        public string                  Vat                   { get; set; }
        public string                  Lido                  { get; set; }
        public string                  CommonArea            { get; set; }
        public string                  HouseClub             { get; set; }
        public string                  Terrace               { get; set; }
        public string                  Garden                { get; set; }
        public string                  MonthlyRent           { get; set; }
        public string                  Conditions            { get; set; }
        public string                  DepositsMonths        { get; set; }
        public string                  Amount                { get; set; }
        public string                  PriceM2               { get; set; }
        public string                  FreeDocument          { get; set; }
        public string                  DocumentNumber        { get; set; }
        public string                  CurrentCredit         { get; set; }
        public string                  BalanceCredit         { get; set; }
        public string                  AssessmentFree        { get; set; }
        public string                  SaleInLast3years      { get; set; }
        public string                  OtherLegalStatus      { get; set; }
        public string                  LightService          { get; set; }
        public string                  WaterService          { get; set; }
        public string                  Lamps                 { get; set; }
        public string                  GasService            { get; set; }
        public string                  SewerSystem           { get; set; }
        public string                  TelephoneService      { get; set; }
        public string                  CableService          { get; set; }
        public string                  Alarm                 { get; set; }
        public string                  ElectricFence         { get; set; }
        public string                  Policy                { get; set; }
        public string                  IrrigationSystem      { get; set; }
        public string                  Nets                  { get; set; }
        public string                  Blinds                { get; set; }
        public string                  Curtains              { get; set; }
        public string                  WaterPressure         { get; set; }
        public string                  AirConditioner        { get; set; }
        public string                  TaxReceipt            { get; set; }
        public string                  Furnished             { get; set; }
        public string                  Guarantor             { get; set; }
        public string                  LegalPolicy           { get; set; }
        public string                  Other1                { get; set; }
        public string                  DeliveryPeriod        { get; set; }
        public string                  Advance               { get; set; }
        public string                  Builder               { get; set; }
        public string                  Development           { get; set; }
        public string                  DirectOwner           { get; set; }
        public string                  Other                 { get; set; }
        public string                  MimeType              { get; set; }
        public string                  Principal             { get; set; }
        public string                  Description1          { get; set; }
        public string                  Url                   { get; set; }
        public string                  MimeType1             { get; set; }
        public string                  Principal1            { get; set; }
        public string                  Url1                  { get; set; }
        public string                  MimeType2             { get; set; }
        public string                  Principal2            { get; set; }
        public string                  Description2          { get; set; }
        public string                  Url2                  { get; set; }
        public string                  MimeType3             { get; set; }
        public string                  Principal3            { get; set; }
        public string                  Description3          { get; set; }
        public string                  Url3                  { get; set; }
        public string                  FechaDeCaptura        { get; set; }
        public string                  Private               { get; set; }
        

    }
}
